### ISSUE TITLE
Attempting to Resuscitate the Application for VR

### ISSUE THREAD

**Issue by DGDC** [ohgodhowdidthis/trance#21]
I am not a C++ developer but really want this application to work with SteamVR (OpenVR). Working on educated guesses and Google Search results I loaded the Jun 4, 2018 projects into Visual Studio Community 2019 on Windows 10 and did the following:

1. Went into properties for each project and set the Windows SDK version the the latest installed version (Configuration Properties > General > Windows SDK Version)
2. Went into properties for each project and set the Language Standard to C++17 (Configuration Properties > C/C++ > Language)
3. Updated Protocol Buffers, https://github.com/protocolbuffers/protobuf
- (Replace \dependencies\x64\protoc.exe with protoc.exe from protoc-x.x.x-win64.zip (and also the Win32 version)
- Replaced \dependencies\include\Google with \src\Google from protobuf-csharp-x.x.x.zip
4. Replaced all instances of "std::tr2::sys" with "std::filesystem" across all files- std::tr2::sys is deprecated and will be removed from C++20

The above steps got me to the following build errors:
1>\trance-master\src\common\session.cpp(256): error C2672: 'std::filesystem::path::append': no matching overloaded function found
1>\trance-master\src\common\session.cpp(256): error C2783: 'std::filesystem::path &std::filesystem::path::append(const _Src &)': could not deduce template argument for '__formal'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\filesystem(790): note: see declaration of 'std::filesystem::path::append'

This is where Google Search has its limitations. I have not yet updated the OpenVR components, https://github.com/ValveSoftware/openvr. Given the above build errors it would be a bit premature to do so.

Is anyone able to assist with getting the app back on its feet for VR?

**Comment by AA10D6** [comment]
I got this working on my fork here https://github.com/AA10D6/trance/commits/master

I updated SFML and OpenVR to latest, and fixed the init and render code for openvr.cpp.

For building, you should just use VS2015 since that's what the project originally targets. You won't get all those build errors you were having if you use it (I had the same problems trying to use 2017 at first which I already had installed). [See here](https://stackoverflow.com/questions/44290672/how-to-download-visual-studio-community-edition-2015-not-2017) for how to get VS2015 since Microsoft doesn't let you download it without jumping through some hoops.

**Comment by DGDC** [comment]
Thanks @AA10D6! I had hoped to get the project updated for 2019 since I know Microsoft is being fairly strict of ending support for older products, but it seems to be too big of a lift.
